### ISSUE TITLE
Collapse details option

### ISSUE THREAD

**Issue by tomberek** [deptofdefense/eMCM#14]
From email submission (name redacted):

'''
Great new product!  The Rules are hard to scroll through once you click on them because of the discussion along side it.  I'm looking at RCM 307 now.  Perhaps collapse the discussions into an expandable link along-side the rule subpart it pertains to, e.g. "Click Here to See Discussion".  Thanks!
R
'''

**Comment by readywater** [comment]
Duplicate #13
