### ISSUE TITLE
Nit picking copyright notices

### ISSUE THREAD

**Issue by marctjones** [deptofdefense/eMCM#19]
My apologies for the nit picking, this might be a better issue for the code.mil repo. I think this is awesome, especially since it is a website for a code of civil procedure (i.e. Manual for Courts-Marshall). But in the spirit of the legal formalism of civil procedure and [Futurama](https://youtu.be/hou0lU8WMgo):

What is the intention of including `Copyright (C) 2017 <Contributor Names>` in the files containing source code? For instance it is included in the header comment of eMCM/js/common.js along with a licensing notice. 

Is it the intention of the U.S. Government to include a copyright notice, since it is anticipated that the code will be available outside of the U.S. were the government holds copyright? Or was this just an example? If it is just an example you might want to consider removing it so as not to cause confusion since it is mixed in with actual licensing information. 

Also I would note the the [statutorily defined](https://www.copyright.gov/title17/92chap4.html) format for a copyright notice is one of three alternatives. 
> (b) Form of Notice.—If a notice appears on the copies, it shall consist of the following three elements:
>  (1) the symbol © (the letter C in a circle), or the word “Copyright”, or the abbreviation “Copr.”; and
>  (2) the year of first publication of the work; in the case of compilations or derivative works incorporating previously published material, the year date of first publication of the compilation or derivative work is sufficient. The year date may be omitted where a pictorial, graphic, or sculptural work, with accompanying text matter, if any, is reproduced in or on greeting cards, postcards, stationery, jewelry, dolls, toys, or any useful articles; and
>  (3) the name of the owner of copyright in the work, or an abbreviation by which the name can be recognized, or a generally known alternative designation of the owner.

So according to the copyright office, see e.g., [Circular 3](https://www.copyright.gov/circs/circ03.pdf), it should be something like:
* Copyright 2017 Copyright Holders Name
* Copy. 2017 Copyright Holders Name
* © 2017 Copyright Holders Name

`(C)` is not actually one of the alternative forms. And your use of the word contributors is also ambiguous since you both recognize that U.S. Gov employees may add themselves to the list of people in the CONTRIBUTORS file and then here suggest the use of the `Contributor Name` next to a copyright notice implying that contributors are copyright holders.

**Comment by shawoods** [comment]
@marctjones Thanks for the feedback! We updated CONTRIBUTORS.md and the source file headers based on your feedback. To the extent we're using (c), we did our best to adopt the syntax conventions of the license we're using, and many licenses used (c) for better or worse. I updated the Code.mil documentation too, so if you have any follow up please jump over there and open an issue. Thanks!
