### ISSUE TITLE
invalid HTML from XML rule nodes

### ISSUE THREAD

**Issue by spoon16** [deptofdefense/eMCM#7]
This HTML is being output in the search results.

```html
<rule <span="" class="highlight">rulenum=""&gt;
  <ol>
    <li index="a">	
      <p>Apprehension is the taking of a person into custody.</p>
    </li>
  </ol>
</rule>
```

This is what it looks like in Chrome 56.0.2924.87 on Windows

![rule xml transformation bug](https://cloud.githubusercontent.com/assets/123686/23839561/33387690-075c-11e7-9564-c4434932ba6f.JPG)

**Comment by tomberek** [comment]
Fixed with 58fee92
The search indexer was being given the raw html.
